// Generated by CoffeeScript 1.9.3

/*
Featured is a section, primarily displayed on the home page that is also
primarily used to show important posts. In addition to supporting showing these
posts featured show's their images. The purpose of this file is to change the
featured image and thus allow for a more concrete navigation.
 */

(function() {
  var featuredImageSelector, imageContainerSelector, postSelector, selectedClass;

  featuredImageSelector = "#featured-image";

  imageContainerSelector = ".post-featured-image";

  postSelector = "#featured .post";

  selectedClass = "selected";

  (function($) {
    return $(document).ready(function() {
      $(imageContainerSelector + " a").each(function() {
        $(this).attr('data-href', $(this).attr('href'));
        $(this).attr('href', null);
        return $(this).css('cursor', 'auto');
      });
      $(postSelector).on('mouseover', function(e) {
        var $featuredContent, id;
        id = $(this).attr('id');
        $featuredContent = $("#featured-image .post-featured-image[data-post-id=" + id + "]");
        $("." + selectedClass).each(function() {
          return $(this).removeClass(selectedClass);
        });
        $featuredContent.addClass(selectedClass);
        return $(this).addClass(selectedClass);
      });
      $(postSelector).each(function() {
        return $(featuredImageSelector).append($(this).find(imageContainerSelector).clone());
      });
      return $(postSelector).first().mouseover();
    });
  })(jQuery);

}).call(this);
