// Generated by CoffeeScript 1.9.3
(function() {
  (function($) {
    return $(function() {
      var $mt, _, createRow, i, nestedNavFunctionality, toggleMoreNav, toggleMoreNavVisible;
      nestedNavFunctionality = function() {
        $('#site-navigation-more a').on('click', function(e) {
          var $t;
          $t = $(this);
          if ($t.siblings('ul').length) {
            $t.parent().click();
            return false;
          }
        });
        return $('#site-navigation-more li').on('click', function() {
          var $children, $currentPage, $p, $t;
          $t = $(this);
          $p = $('#site-navigation-more');
          $p.attr('data-color', $t.index() % 10);
          $children = $t.siblings('ul').length ? $t.siblings('ul') : $t.children('ul');
          $p.html('');
          $p.empty().append($children.clone());
          $currentPage = $('<section class="current-page"></section>').append($t.children('a:first').clone());
          $p.prepend($currentPage);
          return setTimeout(function() {
            $p.children('ul').addClass('come-in');
            return nestedNavFunctionality();
          }, 1);
        });
      };
      toggleMoreNavVisible = function($t) {
        var $p;
        $p = $('#site-navigation-more');
        if ($t.hasClass('clicked')) {
          if (!$p.hasClass('visible')) {
            $p.addClass('visible');
          }
          $('#base-wrapper').addClass('nav-visible');
          $('nav#site-navigation .menu-toggle').cssClick(true);
        } else {
          if ($p.hasClass('visible')) {
            $p.removeClass('visible');
          }
          $('#base-wrapper').removeClass('nav-visible');
          $('nav#site-navigation .menu-toggle').cssClick(false);
          return;
        }
        return $p.attr('data-color', $t.index() % 10);
      };
      toggleMoreNav = function(children) {
        var $children, $currentPage, $p, $t;
        if (children == null) {
          children = [];
        }
        $t = $(this);
        $p = $('#site-navigation-more');
        toggleMoreNavVisible($t);
        $children = $t.siblings('ul').length ? $t.siblings('ul') : $t.children('ul');
        $p.html('');
        $p.empty().append($children.clone());
        $currentPage = $('<section class="current-page"></section>').append($t.children('a:first').clone());
        $p.prepend($currentPage);
        return setTimeout(function() {
          $p.children('ul').addClass('come-in');
          return nestedNavFunctionality();
        }, 1);
      };
      $('nav#site-navigation .menu-toggle').click(function() {
        var $elements, $p, $t;
        $t = $(this);
        $p = $('#site-navigation-more');
        if ($t.hasClass('clicked' && $p.hasClass('visible'))) {
          $p.removeClass('visible');
          $('#base-wrapper').removeClass('nav-visible');
          return true;
        }
        toggleMoreNavVisible($t);
        $elements = $('nav#site-navigation .menu > ul');
        $p.html('');
        $p.empty().append($elements.clone());
        return setTimeout(function() {
          $p.children('ul').addClass('come-in');
          return nestedNavFunctionality();
        }, 1);
      });
      $('nav#site-navigation li').on('click', toggleMoreNav);
      $(document).on('mouseup', function(e) {
        var $c;
        if ($(e.target).is('nav#site-navigation *, #site-navigation-more, #site-navigation-more *')) {
          return true;
        }
        $c = $('#site-navigation-more');
        if (!$c.is(e.target) && $c.has(e.target).length === 0) {
          if ($c.hasClass('visible')) {
            $c.removeClass('visible');
          }
          $('#base-wrapper').removeClass('nav-visible');
          return $('nav#site-navigation li.clicked').each(function() {
            return $(this).click();
          });
        }
      });
      $('nav#site-navigation a').on('click', function(e) {
        var $t;
        $t = $(this);
        if ($t.siblings('ul').length) {
          $t.parent().click();
          return false;
        } else {

        }
      });
      createRow = function(numElems) {
        var row;
        return row = $('<div class="row"></div>');
      };
      if ($('nav#site-navigation .menu-toggle .toggle').length) {
        $mt = $('nav#site-navigation .menu-toggle .toggle');
        for (_ = i = 0; i < 3; _ = ++i) {
          $mt.append(createRow(3));
        }
      }
      $('#sidebar-toggle').click(function() {
        if ($('#base-wrapper').hasClass('sidebar-display')) {
          $('#base-wrapper').removeClass('sidebar-display');
          return $('#sidebar').removeClass('sidebar-display');
        } else {
          $('#base-wrapper').addClass('sidebar-display');
          return $('#sidebar').addClass('sidebar-display');
        }
      });
      return $(document).on('mouseup', function(e) {
        if (!$('#sidebar').is(e.target) && $('#sidebar').has(e.target).length === 0 && $('#sidebar').hasClass('sidebar-display')) {
          return $('#sidebar-toggle').click();
        }
      });
    });
  })(jQuery);

}).call(this);
